### ISSUE TITLE
Error: System.NullReferenceException:

### ISSUE THREAD

**Issue by NyxmeFy** [vandernorth/NecroBot.GUI#130]
### Issue or feature request?
[10:35:00] New update detected, would you like to update? Y/N
[10:35:00] Pokemon Servers might be offline / unstable. Trying again...
[10:35:01] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.State.VersionCheckState.<Execute>d__4.MoveNext() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\State\VersionCheckState.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57

### Other Information
Version: 0.5.1
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by vandernorth** [comment]
Ah yeah.... stupid... 

workaround: in your config set "CheckForUpdates" to false
