### ISSUE TITLE
I have only this error now, everything else is ok

### ISSUE THREAD

**Issue by antibiotic1** [vandernorth/NecroBot.GUI#131]
[2016-08-21 17:24:26] (Info) There is no workspace.xml in your root directory to load.
[2016-08-21 17:24:31] (Info) Your IP is: 217.196.206.165
[2016-08-21 17:24:32] (Update) Perfect! You already have the newest Version 0.9.4
[2016-08-21 17:24:32] (Info) Logging in using Ptc
[2016-08-21 17:24:34] (Error) System.MissingMethodException: Method not found: 'Void POGOProtos.Networking.Envelopes.RequestEnvelope.set_Unknown6(POGOProtos.Networking.Envelopes.Unknown6)'.
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(Request[] customRequests)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(RequestType type, IMessage message) in C:\Users\User\Documents\GitHub\NecroBot.GUI\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 234
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in C:\Users\User\Documents\GitHub\NecroBot.GUI\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__3.MoveNext() in C:\Users\User\Documents\GitHub\NecroBot.GUI\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Player.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() in C:\Users\User\Documents\GitHub\NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 181

In the cmd window in you UI i only get this error. I finaly managed to start it with integrating the latest necrobot but only this error ocours
Any help?

**Comment by vandernorth** [comment]
Thats a bug in the latest necrobot, did you check out the latest commit or the commit for release v0.9.4?

**Comment by vandernorth** [comment]
Found it, its the config, KillSwitchSettings is new and null by default. just put this in your config:
`KillSwitchSettings:{}
