### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by jimmyxXx** [vandernorth/NecroBot.GUI#142]
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57

**Comment by richie86** [comment]
same here for the latest release build

**Comment by cmgabe** [comment]
same here

**Comment by vandernorth** [comment]
This is in necrobot, possible fixed in latest version.
