### ISSUE TITLE
[feature request] start from last position

### ISSUE THREAD

**Issue by golgolak** [vandernorth/NecroBot.GUI#153]
### Issue or feature request?
feature request

### Expected Behavior
when the bot is restarted, start from last known position, add a flag startfromlastposition: true/false.

### Actual Behavior
whenever below error is encountered, the bot re-login and starts from the default coords. when using gpx path or wide distance ratio, this could easily be flagged as the bot just teleported. below happens like every 20-30mins. I believe it is already reported so i'm not posting a new one for this error.

[12:06:03] Pokemon Servers might be offline / unstable. Trying again...
[12:06:04] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.<Execute>d__3.MoveNext() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57

### Steps to Reproduce
it happens every 20-30mins

### Other Information
Version: 0.5.2
Windows Version: win10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by vandernorth** [comment]
I believe this is added in the latest (or the one before) necrobot.

**Comment by golgolak** [comment]
Ah yes. Thanks. Gave u admin rights to discord
