### ISSUE TITLE
help, stuck login this message error

### ISSUE THREAD

**Issue by hanncreator** [vandernorth/NecroBot.GUI#35]
nitializing NecroBot logger at time 14/08/2016 12:14:52...
Initializing NecroBot logger at time 14/08/2016 12:16:04...
Initializing NecroBot logger at time 14/08/2016 12:17:34...
Initializing NecroBot logger at time 14/08/2016 12:18:07...
Initializing NecroBot logger at time 14/08/2016 12:18:14...
[12:17:35] JSON Exception: You need to properly configure your GoogleUsername using quotations.
[12:17:36] Perfect! You already have the newest Version 0.8.6
[12:17:36] Logging in using Google
[12:17:36] You need to fill out GoogleUsername and GooglePassword in auth.json!
[12:17:36] System.NullReferenceException: Object reference not set to an instance of an object.
at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformAuthRequest(Dictionary2 data) at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformMasterLogin(String service, String deviceCountry, String operatorCountry, String lang, Int32 sdkVersion) at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__3.MoveNext() in C:\webstorm\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 30 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\webstorm\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 43 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() [12:17:36] System.ArgumentNullException: Value cannot be null. Parameter name: message at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name) at Google.Protobuf.MessageExtensions.ToByteArray(IMessage message) at PokemonGo.RocketAPI.Helpers.RequestBuilder.GenerateSignature(IEnumerable1 requests) in C:\webstorm\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 95
at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(Request[] customRequests) in C:\webstorm\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 153
at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(RequestType type, IMessage message) in C:\webstorm\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 202
at PokemonGo.RocketAPI.Rpc.BaseRpc.d__6`2.MoveNext() in C:\webstorm\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at PokemonGo.RocketAPI.Rpc.Player.d__3.MoveNext() in C:\webstorm\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Player.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at PoGo.NecroBot.Logic.State.LoginState.d__2.MoveNext()
[12:17:56] Due to login failure your player profile could not be retrieved. Press any key to re-try login.
[12:17:56] Pokemon Servers might be offline / unstable. Trying again...
[12:17:57] Error: System.NullReferenceException: Object reference not set to an instance of an object.
at PoGo.NecroBot.Logic.State.LoginState.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwait

**Comment by vandernorth** [comment]
Please read this line from your log carefully:

JSON Exception: You need to properly configure your GoogleUsername using quotations.
