### ISSUE TITLE
FarmPokestopsTask.cs:line 78

### ISSUE THREAD

**Issue by zathrath03** [vandernorth/NecroBot.GUI#79]
I've been getting this error every 10-20 minutes always the same second as using a pokestop.
```
[22:57:37] Name: Raven Night Love  
 - XP:    50 
 - Gems:  0 
 - Items: 2 x ItemPokeBall, 1 x ItemSuperPotion
[22:57:37] Pokemon Servers might be offline / unstable. Trying again...
[22:57:38] Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\webstorm\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\webstorm\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\webstorm\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 56
[22:57:38] Logging in using Google
```

My config is included:
[config.txt](https://github.com/vandernorth/NecroBot.GUI/files/421691/config.txt)

**Comment by zappiy** [comment]
Isnt that a ban.

**Comment by RuneMykle** [comment]
Well, it's not a gui problem at least, would be better to ask here: https://github.com/NoxxDev/NecroBot/issues

**Comment by vandernorth** [comment]
What @RuneMykle said..
Closing this issue.
